#!/bin/bash

# only run on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "Skipping Ghostty configuration (macOS only)"
    exit 0
fi


# set up ghostty config
GHOSTTY_CONFIG_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
mkdir -p "$GHOSTTY_CONFIG_DIR"

# create config file with settings
cat > "$GHOSTTY_CONFIG_DIR/config" << 'EOL'
# Config generated by Ghostty Config

window-colorspace = display-p3
theme = catppuccin-macchiato
background = #24273a
foreground = #cad3f5
selection-background = #5b6078
selection-foreground = #cad3f5
selection-invert-fg-bg = true
cursor-color = #f4dbd6
cursor-text = #cad3f5
palette = 0=#494d64
palette = 1=#ed8796
palette = 2=#a6da95
palette = 3=#eed49f
palette = 4=#8aadf4
palette = 5=#f5bde6
palette = 6=#8bd5ca
palette = 7=#a5adcb
palette = 8=#5b6078
palette = 9=#ec7486
palette = 10=#8ccf7f
palette = 11=#e1c682
palette = 12=#78a1f6
palette = 13=#f2a9dd
palette = 14=#63cbc0
palette = 15=#b8c0e0
font-size = 14
font-thicken = true
font-family = Jetbrains Mono
EOL

echo "Ghostty configuration complete!"